version: '3.5'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:80  # can't bind on 80 since that requires sudo
      # - 8000:8000

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      - API_URL=http://localhost:8080/api

  backend:
    image: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./logs.txt:/app/backend-example-docker/logs.txt:rw
    restart: 'unless-stopped'
    depends_on:
      - redis
      - db
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=backendme
      - DB_HOST=db  # use db's ipaddr

  redis:
    image: redis

  db:
    image: postgres
    restart: 'unless-stopped'
    environment:
      - POSTGRES_PASSWORD=backendme
